name: Release

on:
  push:
    branches:
      - main

jobs:

  information:
    name: GitHub Context
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "$GITHUB_CONTEXT"
    

  generate_git_release:
    needs: generate_git_tags
    name: 'GitHub Release'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release Action
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ needs.generate_git_tags.outputs.output_new_tag }}
          token: ${{ secrets.CHANGELOG_RELEASE }}


  generate_sentry_release:
    needs: [generate_git_tags, generate_git_release]
    name: Sentry Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Split Repo Name
        uses: jungwinter/split@v2
        id: split_repo_name
        with:
          msg: ${{ github.repository }} 
          separator: "/"
          maxsplit: 1
      - name: Echo Repo Name
        run: echo "${{ steps.split_repo_name.outputs._1 }}"
      - name: Sentry Release
        uses: getsentry/action-release@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}
        with:
          environment: production
          version: "s{{steps.split_repo_name.outputs._1}}@${{needs.generate_git_tags.outputs.output_new_tag}}"
          sourcemaps: "./dist"
          url_prefix: "~"